export default [
    'Lock on bedroom door',
    'Kitchen',
    'Dedicated workspace',
    'Free washer - In unit',
    'Free dryer – In unit',
    'Elevator',
    'Free parking on premises',
    'Fast wifi',
    'Courtyard view',
    'Hair dryer',
    'Air conditioning',
    'Hot tub',
    'Smoke alarm',
    'Security cameras on property',
    'Luggage dropoff allowed',
    'Carbon monoxide alarm',
    'Pool',
]