import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import { getExploreNearby } from '@/lib/getExploreNearby'
import SmallCard from '@/components/SmallCard'
import { getCardsData } from '@/lib/getCardsData'
import MediumCard from '@/components/MediumCard'


export default function Home({exploreData, cardsData}) {
  return (
    <div className=''>
      <Head>
        <title>HavirBnB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <Banner />

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='text-4xl font-bold pb-5'>Explore Nearby</h2>

          <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
            {exploreData?.map((i, index) => (
              <SmallCard key={index} img={i.img} distance={i.distance} location={i.location} />
            ))}
          </div>


        </section>

        <section className='p'>
          <h2 className='text-4xl font-bold pb-5'>Live Anywhere</h2>

          <div className='flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3'>
            {cardsData?.map((i, index) => (
              <MediumCard key={index} img={i.img} title={i.title} />
            ))}
          </div>


        </section>


      </main>
    </div>
  )
}


export async function getStaticProps() {
  const exploreData = await getExploreNearby()

  const cardsData = await getCardsData()

  return {
    props: {exploreData, cardsData}
  }
}